const IMAGES = {
  Splash: require('./SplashImage.png'),
  AppIcon: require('./AppIcon.png'),
  KidsImage: require('./KidsImage.png'),
  kidsImageOne: require('./Kidsimage1.png'),
  Image: require('./Image.png'),
  GlobalImage: require('./GlobalImage.png'),
  MissionImage: require('./MissionImage.png'),
  JoinImage: require('./JoinImage.png'),
  AppLogoImage: require('./AppLogoImage.png'),
  Badge: require('./Badge.png'),
  OnePaliLogo: require('./OnePaliLogo.png'),
  SeedBadge: require('./SeedBadge.png'),
  FeedImage: require('./FeedImage.png'),
  Sprout1 : require('./SproutOne.png'),
  Sprout2 : require('./Sprout2.png'),
  Sprout3 : require('./Sprout3.png'),
  BadgeLogo : require('./BadgeLogo.png'),
  Skrim : require('./Skrim.png'),
  SpeakerBadge : require('./SpeakerBadge.png'),
  Paliroot: require('./Paliroot.png'),
  MecaImage: require('./MecaImage.png'),
  seedsOne: require('./seedOne.png'),
  FounderSeed : require('./FounderSeed.png'),
  JaffaSeed : require('./JaffaSeed.png'),
  EchoSeed : require('./EchoSeed.png'),
  InviteFriends : require('./InviteFriends.png'),
  ClaimCard : require('./ClaimCard.png'),
  SupportImage :  require('./SupportImage.png'),
  LoopImage : require('./LoopImage.png'),
};

export default IMAGES