const IMAGES = {
  KidsImage: require("./KidsImage.png"),
  kidsImageOne: require("./Kidsimage1.png"),
  Image: require("./Image.png"),
  MissionImage: require("./MissionImage.png"),
  JoinImage: require("./JoinImage.png"),
  OnePaliLogo: require("./OnePaliLogo.png"),
  Paliroot: require("./Paliroot.png"),
  MecaImage: require("./MecaImage.png"),
  ClaimCard: require("./ClaimCard.png"),
  SupportImage: require("./SupportImage.png"),
  LoopImage: require("./LoopImage.png"),
  ChangedSplash: require("./ChangedSplash.png"),
  LogoText: require("./LogoText.png"),
  BadgeGreenBg: require("./BadgeGreenBg.png"),
  BadgeBrownBg: require("./BadgeBrownBg.png"),
  BadgePinkBg: require("./BadgePinkBg.png"),
  BadgeBlackBg: require("./BadgeBlackBg.png"),
  ImageLike: require("./ImageLike.png"),
  SplashInitial: require("./SplashInitial.png"),
  HomeTextBackgorund: require("./HomeTextBackgorund.png"),
  EarnBadgs: require("./EarnBadges.png"),
};

export default IMAGES;
